### ISSUE TITLE
Namespace changes

### ISSUE THREAD

**Issue by wvanheumen** [NoxxieNl/Nladdresslexer#10]
First of all, thank you for this nice library. Make my life a bit easier!

I do want to mention that in version 1.1.1 there was a change in namespace.  This should not be done in a minor/patch level update.

Just making sure it won't happen again, since it will break stuff :-)

**Comment by NoxxieNl** [comment]
Yeah...

I am still learning some tweaking regarding semver :-).
Thx for saying it!

I released version 2.x that is breaking ;-)!
