### ISSUE TITLE
support for doctrine lexer 3.0.0

### ISSUE THREAD

**Issue by henzeb** [NoxxieNl/Nladdresslexer#11]
Will there be support for doctrine lexer v3.0.0? I am currently trying this on a new clean laravel 10 install. 

a workaround is to use the --with-all-dependencies.

doctrine lexer 3.0 is required by egulias/email-validator which in turn is required  by the framework and symfony mailer. As my project does not require email validation at the time, this is a non-issue for me, but there may be changes in newer versions on which one may lean on.

**Comment by NoxxieNl** [comment]
Hi @henzeb,

I upgraded the package to version 2.x to activate support for v3.x  doctrine/lexer.
The default branch is now 2.x.x for this.
