### ISSUE TITLE
Error while executing install

### ISSUE THREAD

**Issue by drummerik** [NoxxieNl/Nladdresslexer#3]
Hi, 
I'm getting an error while executing:

composer require noxxienl/nladdressparser

error:
[InvalidArgumentException]                                                                                                           
  Could not find a matching version of package noxxienl/nladdressparser. Check the package spelling, your version constraint and that  
   the package is available in a stability which matches your minimum-stability (stable).

**Comment by henzeb** [comment]
Will that ever be fixed in the documentation? just like I am supposed to use AddressParser instead of Parser?

**Comment by NoxxieNl** [comment]
> Will that ever be fixed in the documentation? just like I am supposed to use AddressParser instead of Parser?

It is now :) v1.1.1 just released.
