### ISSUE TITLE
Not working for address: Lange Nieuwstraat 34 bus 306

### ISSUE THREAD

**Issue by michiellucas** [NoxxieNl/Nladdresslexer#9]
Not working for address: Lange Nieuwstraat 34 bus 306

this returns street: 
^ "Lange Nieuwstraat 34 bus"

and number 306

**Comment by NoxxieNl** [comment]
Good morning,

As far as I can see "Lange Nieuwstraat 34 bus 306" is not a address from the Netherlands but rather from Belgium.

What you could do is extend the `StreetsWithEndNumber` class and add the address yourself how you want to parse it correctly.
